import { Component } from "@angular/core";
import { ExcelService } from "./excel.service";

@Component({
  selector: "app-root",
  templateUrl: "./app.component.html",
  styleUrls: ["./app.component.css"],
})
export class AppComponent {
  constructor(private excelService: ExcelService) {}
  data = [
    [
      "",
      36,
      "Conductor",
      "Casing",
      30,
      534.8,
      984.3,
      543.8,
      534.8,
      984.3,
      543.8,
      8.35,
      "",
      "",
      "Failed to load",
    ],
    [
      "",
      36,
      "Conductor",
      "Casing",
      30,
      534.8,
      984.3,
      543.8,
      534.8,
      984.3,
      543.8,
      8.35,
      "",
      "",
      "Failed to load",
    ],
    [
      "",
      36,
      "Conductor",
      "Casing",
      30,
      534.8,
      984.3,
      543.8,
      534.8,
      984.3,
      543.8,
      8.35,
      "",
      "",
      "Failed to load",
    ],
    [
      "",
      36,
      "Conductor",
      "Casing",
      30,
      534.8,
      984.3,
      543.8,
      534.8,
      984.3,
      543.8,
      8.35,
      "",
      "",
      "Failed to load",
    ],
    [
      "",
      36,
      "Conductor",
      "Casing",
      30,
      534.8,
      984.3,
      543.8,
      534.8,
      984.3,
      543.8,
      8.35,
      "",
      "",
      "Failed to load",
    ],
  ];
  generateExcel() {
    // this.excelService.generateExcel();
    this.excelService.exportToExcelHoldSections({
      myData: this.data,
      fileName: "Hole Sections Summary",
      sheetName: "sheet1",
      sheetTitle: "Hole Sections Summary",
      tableTitle: "Hole Sections",
      myHeader: [
        "",
        "Hole Size(in)",
        "Name",
        "String Type",
        "Casing OD(in)",
        "Measured Depth (ft)",
        "TVD (ft)",
        "Mud Density (ppg)",
        "Fluid Type",
        "Lithology at Shoe",
        "Kick Tolerance (bbl)",
      ],
      bottomHeader: ["Top", "Shoe", "TOC"],
      widths: [
        { width: 12 },
        { width: 10 },
        { width: 15 },
        { width: 15 },
        { width: 15 },
        { width: 15 },
        { width: 15 },
        { width: 15 },
        { width: 15 },
        { width: 15 },
        { width: 15 },
        { width: 15 },
        { width: 15 },
        { width: 15 },
        { width: 20 },
      ],
    });
  }
}
